# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guessNumberWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class guessNumberUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(100, 50, 661, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(90, 60, 20, 451))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(100, 500, 661, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(750, 60, 20, 451))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 320, 601, 181))
        self.label.setStyleSheet("font: 10pt \"微软雅黑\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 110, 91, 21))
        self.label_2.setObjectName("label_2")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(300, 60, 20, 241))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(100, 290, 661, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 170, 91, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(400, 110, 191, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(400, 170, 191, 121))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_confirm.setGeometry(QtCore.QRect(610, 110, 75, 23))
        self.pushButton_confirm.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_confirm.setStyleSheet("background-color: rgb(170, 255, 0);")
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(120, 70, 161, 231))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_start = QtWidgets.QPushButton(self.widget)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_start.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"font: 12pt \"Agency FB\";")
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.pushButton_control = QtWidgets.QPushButton(self.widget)
        self.pushButton_control.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"font: 12pt \"Agency FB\";")
        self.pushButton_control.setObjectName("pushButton_control")
        self.verticalLayout.addWidget(self.pushButton_control)
        self.pushButton_exit = QtWidgets.QPushButton(self.widget)
        self.pushButton_exit.setStyleSheet("background-color: rgb(170, 255, 0);\n"
"font: 12pt \"Agency FB\";")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.verticalLayout.addWidget(self.pushButton_exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "游戏规则说明：\n"
"1）从0~9中选取X个不重复的数字，视为猜数字，一共有Y次竞猜机会（X,Y可以在游戏设置中调整）；\n"
"2）每猜一次，系统会返回当前猜数字的结果，用A和B来代替，以下以X=4来举例：\n"
"①如果有一个数字和位置都猜对了，记作1A，如果有一个数字猜对了但位置错了，记作1B，\n"
"A的优先级比B高（意思就是已经记作A的数字，不会再统计B）\n"
" ②当所有数字和位置都正确时，记作4A0B，玩家胜利；当所有数字都正确但位置都错误时，记作0A4B；\n"
"如果所有数字都没有猜对，记作0A0B。\n"
"③请充分利用数字不能重复和系统返回的猜数字结果，猜想你心中的答案吧。祝你好运！"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">输入内容</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "显示结果"))
        self.pushButton_confirm.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">确定</span></p></body></html>"))
        self.pushButton_confirm.setText(_translate("MainWindow", "确定"))
        self.pushButton_start.setText(_translate("MainWindow", "开始游戏"))
        self.pushButton_control.setText(_translate("MainWindow", "游戏设置"))
        self.pushButton_exit.setText(_translate("MainWindow", "退出游戏"))
        self.menu.setTitle(_translate("MainWindow", "猜数字"))
