# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'outputSalesWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OutputSales(object):
    def setupUi(self, OutputSales):
        OutputSales.setObjectName("OutputSales")
        OutputSales.setEnabled(True)
        OutputSales.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/group2/img/lele.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        OutputSales.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(OutputSales)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(100, 50, 661, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(90, 60, 20, 261))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(750, 60, 20, 451))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(100, 310, 661, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(130, 150, 521, 51))
        self.progressBar.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(320, 100, 151, 28))
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_start.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"font: 12pt \"Agency FB\";")
        self.pushButton_start.setObjectName("pushButton_start")
        OutputSales.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OutputSales)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        OutputSales.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OutputSales)
        self.statusbar.setObjectName("statusbar")
        OutputSales.setStatusBar(self.statusbar)
        self.action_start = QtWidgets.QAction(OutputSales)
        self.action_start.setObjectName("action_start")
        self.action_exit = QtWidgets.QAction(OutputSales)
        self.action_exit.setObjectName("action_exit")
        self.action_help = QtWidgets.QAction(OutputSales)
        self.action_help.setObjectName("action_help")
        self.action = QtWidgets.QAction(OutputSales)
        self.action.setObjectName("action")
        self.action_mute = QtWidgets.QAction(OutputSales)
        self.action_mute.setObjectName("action_mute")
        self.menu_2.addAction(self.action_mute)
        self.menu_2.addAction(self.action_help)
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(OutputSales)
        QtCore.QMetaObject.connectSlotsByName(OutputSales)

    def retranslateUi(self, OutputSales):
        _translate = QtCore.QCoreApplication.translate
        OutputSales.setWindowTitle(_translate("OutputSales", "猜数字"))
        self.pushButton_start.setText(_translate("OutputSales", "选择交易文件"))
        self.menu_2.setTitle(_translate("OutputSales", "选项"))
        self.action_start.setText(_translate("OutputSales", "开始"))
        self.action_exit.setText(_translate("OutputSales", "退出"))
        self.action_help.setText(_translate("OutputSales", "关于"))
        self.action.setText(_translate("OutputSales", "静音"))
        self.action_mute.setText(_translate("OutputSales", "静音"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OutputSales = QtWidgets.QMainWindow()
    ui = Ui_OutputSales()
    ui.setupUi(OutputSales)
    OutputSales.show()
    sys.exit(app.exec_())
